export const CATEGORIES = [
    { value: "", label: "All Categories" },
    { value: "data-science", label: "Data Science" },
    { value: "design-multimedia", label: "Design & Multimedia" },
    { value: "dev", label: "Development" },
    { value: "seo", label: "SEO" },
    { value: "engineering", label: "Engineering" },
    { value: "web-app-design", label: "Web App Design" },
]

export const LOCATIONS = [
    { value: "", label: "Any Location" },
    { value: "argentina", label: "Argentina" },
    { value: "australia", label: "Australia" },
    { value: "austria", label: "Austria" },
    { value: "belgium", label: "Belgium" },
    { value: "brazil", label: "Brazil" },
    { value: "bulgaria", label: "Bulgaria" },
    { value: "canada", label: "Canada" },
    { value: "china", label: "China" },
    { value: "costa-rica", label: "Costa Rica" },
    { value: "croatia", label: "Croatia" },
    { value: "cyprus", label: "Cyprus" },
    { value: "czechia", label: "Czechia" },
    { value: "denmark", label: "Denmark" },
    { value: "estonia", label: "Estonia" },
    { value: "europe", label: "Europe" },
    { value: "finland", label: "Finland" },
    { value: "france", label: "France" },
    { value: "germany", label: "Germany" },
    { value: "greece", label: "Greece" },
    { value: "hong-kong", label: "Hong Kong" },
    { value: "hungary", label: "Hungary" },
    { value: "ireland", label: "Ireland" },
    { value: "israel", label: "Israel" },
    { value: "italy", label: "Italy" },
    { value: "japan", label: "Japan" },
    { value: "latvia", label: "Latvia" },
    { value: "lithuania", label: "Lithuania" },
    { value: "mexico", label: "Mexico" },
    { value: "netherlands", label: "Netherlands" },
    { value: "new-zealand", label: "New Zealand" },
    { value: "norway", label: "Norway" },
    { value: "philippines", label: "Philippines" },
    { value: "poland", label: "Poland" },
    { value: "portugal", label: "Portugal" },
    { value: "romania", label: "Romania" },
    { value: "serbia", label: "Serbia" },
    { value: "singapore", label: "Singapore" },
    { value: "slovakia", label: "Slovakia" },
    { value: "slovenia", label: "Slovenia" },
    { value: "south-korea", label: "South Korea" },
    { value: "spain", label: "Spain" },
    { value: "sweden", label: "Sweden" },
    { value: "switzerland", label: "Switzerland" },
    { value: "thailand", label: "Thailand" },
    { value: "turkiye", label: "Türkiye" },
    { value: "united-arab-emirates", label: "UAE" },
    { value: "uk", label: "UK" },
    { value: "ukraine", label: "Ukraine" },
    { value: "usa", label: "USA" },
    { value: "vietnam", label: "Vietnam" },
]

export const SENIORITIES = [
    { value: "", label: "Any Seniority" },
    { value: "entry", label: "Junior / Entry" },
    { value: "midweight", label: "Midweight" },
    { value: "senior", label: "Senior" },
    { value: "lead", label: "Lead" },
    { value: "manager", label: "Manager" },
    { value: "director", label: "Director" },
    { value: "executive", label: "Executive / VP" },
]
